version: '3.8'

services:
  caddy:
    # For local development, it falls back to 'taeho9/caddymanger'.
    image: ghcr.io/taeho9/caddymanager/caddy-maxmind-crowdsec:latest
    container_name: caddy
    restart: always
    ports:
      # for Home NAS
      # - "8880:80"
      # for OCI
      - "80:80"      
      - "443:443"
    environment:
      - TZ=Asia/Seoul
      - XDG_CONFIG_HOME=/config
      - XDG_DATA_HOME=/data
      - CROWDSEC_API_KEY=1qaz@WSX3edc 
    volumes: # (for OCI)
      - /data/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /data/caddy/data:/data
      - /data/caddy/config:/config
      - /data/caddy/logs:/var/log/caddy
    # volumes: # (for Synology)
    #   - /volume1/docker/caddy/data:/data:rw
    networks:
      - reverse_proxy
    depends_on:
      - caddy-gui
      - crowdsec

  caddy-gui:
    image: ghcr.io/taeho9/caddymanager/caddy-gui:latest
    container_name: caddy-gui
    hostname: caddy-gui
    restart: unless-stopped
    volumes: # (for OCI)
      - /data/caddy/Caddyfile:/app/Caddyfile
      - /var/run/docker.sock:/var/run/docker.sock
    # volumes: # (for Synology)
    #   - /volume1/docker/caddy/Caddyfile:/app/Caddyfile
    networks:
      - reverse_proxy

  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    restart: unless-stopped
    environment:
      - TZ=Asia/Seoul
      # Caddy 방어 시나리오 및 리눅스 기본 방어 시나리오 자동 다운로드
      - COLLECTIONS=crowdsecurity/caddy crowdsecurity/base-http-scenarios crowdsecurity/linux
      # Caddy에 설정한 것과 동일한 API 키 입력
      - BOUNCER_KEY_CADDY=my_super_secret_bouncer_key_123
    volumes:
      - /data/caddy/crowdsec/db:/var/lib/crowdsec/data/
      - /data/caddy/crowdsec/config:/etc/crowdsec/
      # Caddy 로그를 읽기 전용(ro)으로 가져옴
      - /data/caddy/logs:/var/log/caddy:ro
      # 로그 수집기 설정 파일 마운트 (컨테이너 실행 전 호스트에 파일이 있어야 함)
      - /data/caddy/crowdsec/acquis.d/caddy.yaml:/etc/crowdsec/acquis.d/caddy.yaml:ro
    networks:
      # Caddy와 통신할 수 있도록 동일한 리버스 프록시 네트워크에 배치
      - reverse_proxy
    security_opt:
      - no-new-privileges:true

networks:
  reverse_proxy:
    name: reverse_proxy
    external: true